### ISSUE TITLE
Database missing for sample site

### ISSUE THREAD

**Issue by ismailmayat** [Philo/Umbraco.Elasticsearch#23]
Is it possible to get copy of db for sample site so we can run it?

Regards

Ismail

**Comment by Philo** [comment]
Doh! - bad gitignore to blame here.  I'll look at updating it and pushing the sample db's

**Comment by Philo** [comment]
In the mean time this is the `umbraco.sdf` for the v75 sample project.

[Umbraco.zip](https://github.com/Philo/Umbraco.Elasticsearch/files/2552962/Umbraco.zip)

**Comment by ismailmayat** [comment]
Awesome cheers Phil. Have just fixed my issue. We had index we were keying
on a guid property from our doc type. What we found was unpublish and
delete were not removing items from index. Turned out we needed to over
ride the IdFor method now its looking good.

Many thanks

Ismail

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
