### ISSUE TITLE
How to set analyser during indexing

### ISSUE THREAD

**Issue by ismailmayat** [Philo/Umbraco.Elasticsearch#25]
Phil,

How do i set an analyser during the index create / indexing process?  Nothing is set at the moment and I am guessing the default is keyword.  I want to add lowercase filter.  

Regards

Ismail

**Comment by Philo** [comment]
Hi Ismail,

The key here to create an implementation of:

https://github.com/Philo/Umbraco.Elasticsearch/blob/master/src/Umbraco.Elasticsearch.Core/Impl/ElasticsearchIndexCreationStrategy.cs

Then override the `WithCreateIndexDescriptor` method to receive an instance of the NEST `CreateIndexDescriptor`.  From here you can configure your index creation in whatever way you need.

Then from your implementation of `SearchApplicationEventHandler` return your `ElasticsearchIndexCreationStrategy` implementation using the `GetIndexCreationStrategy` (https://github.com/Philo/Umbraco.Elasticsearch/blob/master/src/Umbraco.Elasticsearch.Core/EventHandlers/SearchApplicationEventHandler_Configure.cs#L83).

See the sample for a basic example that doesn't apply any customisation within its index creation strategy:

https://github.com/Philo/Umbraco.Elasticsearch/blob/master/samples/Umbraco.Elasticsearch.Samplev75/Features/Search/UmbracoElasticsearchStartup.cs#L23

Apologies the documentation is particularly weak around this point of customisation.  I can provide a more real world example of an `IndexCreationStrategy` if that would be helpful?
