### ISSUE TITLE
UmbracoaHelper used as a singleton 

### ISSUE THREAD

**Issue by Shazwazza** [Philo/Umbraco.Elasticsearch#6]
I'm not positive, but after quickly looking at some code it seems you might be using UmbracoHelper as a singleton in your IndexService. If your Index service class is request scoped or transient than its usage is fine but otherwise you'll run into problems because the UmbracoContext is a request scoped object which is used to create the helper.

**Comment by Philo** [comment]
Thanks for the comment @Shazwazza.  The `IndexService` is a base class under both the `ContentIndexService` and `MediaIndexService`, who themselves are expected to be derived from to create content type specific services (e.g. `ArticleContentIndexService`) that supply any custom logic for transforming a content/media node into an Elasticsearch document for indexing.

All of the *IndexService objects will be request scoped as they are all called via backoffice API's to create and build content and media indices interactively...

![image](https://cloud.githubusercontent.com/assets/432217/16879821/3e7af466-4aaa-11e6-8439-5a255147f42d.png)

The only scenario I'm yet to test is when a scheduled publish occurs, however I believe that scheduled publishing is triggered via a REST API call itself so will also be request scoped?

The library is still a work in progress and is not designed to be a drop in replacement for any Examine functionality on the front end, but instead to give the developer as much flexibility as possible when iot comes to indexing and searching with Umbraco acting as the data source.

**Comment by Shazwazza** [comment]
Ok great, just wanted to make sure you were aware in case these services weren't request or transient scoped - bad things can happen then if turning an UmbracoHelper into a singleton :)

Defo an interesting project, we've been working on this: http://issues.umbraco.org/issue/U4-2676 which will basically make the search in the back office very abstracted so devs could replace the entire thing if they wanted. I also have TODO note to make an Examine provider for Elastic search/Azure search, which should be possible especially since they both support raw lucene queries. That said, Examine certainly has it's limitations so nice to see new options like this for front-end searching. Examine v2 is much more flexible but will still lack some functionality when it comes to specific searching/indexing - you can only go so far to abstract something like that :) In the future once the back office search is abstracted (i.e. provide list of search results for a string) we'd like to have an event listener class for indexing, which means devs could just implement an interface and the method would be called whenever we know index data would need to change (i.e. created, updated, deleted, content type alias changed, property type alias changed, etc..) since there's quite a lot of circumstances to think about which we have in place and it'd be much nicer to just implement a single interface to know what they are.  (hope that makes sense!)

**Comment by Philo** [comment]
It would be great to have enough abstraction to allow more specific custom search implementations, I guess there are 2 major user stories here:
1. The ability to use something other than Examine/lucene as the primary backoffice search mechanism
2. The ability to integrate a custom search implementation for use on the front end, where the search requirements could be endlessly different on a per project basis.

I'm not looking to create something that replaces any of the back end search functions, instead in its much basic form I'm just trying to create a flexible interface between Umbraco as a data source and at present Elasticsearch.

My key requirements from Umbraco in this regard are simple points of abstraction over the content so I can be notified of change.  While the current publishing events are working to that end there are a few gotchas around new content that isnt yet in the cache and subsequently doesnt have a url.

A lot of the projects I work on have used Elasticsearch as a data store and/or search platform, but its only more recently that I've started working with Umbraco as well, with a lot of our clients looking for for a fully loaded CMS and a complex search and discovery based front end with complex querying requirements such as:
- Auto complete / Did you mean
- hierarchical facetting and aggregation
- highly customised text and token analysis

All of which leads to needing significant control of the index creation strategy as well as total control over the structure of the indexed document.

Our bespoke solutions use, [Nest-Queryify](https://github.com/stormid/nest-queryify), [Nest-Indexify](https://github.com/stormid/nest-indexify) and [Nest-Searchify](https://github.com/stormid/nest-searchify) to interact with Elasticsearch.

Once I have time to write up some sensible how-to guides for using the library I'm keen to publicise it more and get greater feedback.

**Comment by Shazwazza** [comment]
Yup that all makes perfect sense. I think having Umbraco tell you via an interface what is changing would go a long way to stream lining that procedure. 

It's very worth noting that the published content stuff you mention, and timings, etc (which is why i are using the Umbraco helper to begin with i think) can basically all be ignored. All data query ing to get index data should go straight to the service layer, not the front end cache. This is changed in examine in umb 7.5 to do this too, once that is out i can show you what i mean and it will make all data access and events linear

**Comment by Philo** [comment]
Absolutely, anything that could simplify the process of receiving notification of change would be good, if that detachment from the helper opens up the ability to parallelise the process that would be even better.
