### ISSUE TITLE
A question about rebuild of indices

### ISSUE THREAD

**Issue by doronuziel71** [Philo/Umbraco.Elasticsearch#7]
Just found out this project and am really excited. I came in a perfect time as I am working on a project with tons of content nodes, a need for geolocation searches, faceted searches, and some advanced lucene features that do not exist on 2.9.4. 

Just a quick question - why cant I rebuild the indices once are active?  It seems to me that this is a common task I would like to carry out through dev, or when deploying a new feature. 

Thanks in advance
Doron

**Comment by doronuziel71** [comment]
Just figured it out. You can have many indices. So when I wish to rebuild I add a new one, build it and then turn it into the active one. 

Very smart

**Comment by Philo** [comment]
Hi @doronuziel71 - glad to see that others may find this integration useful.

As you say the intention is that you can re-build your indices without affecting the currently active one, allowing for increased uptime.

As you have probably noticed there is a lack of documentation at the moment (outside the sample project) and I need to find time to rectify this, if however in the mean time you have any questions please feel free to raise them as issues and I will be happy to help

**Comment by Philo** [comment]
Just to follow up and close this issue, documentation has started to happen in the project [wiki](https://github.com/Philo/Umbraco.Elasticsearch/wiki)
